[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "scatseisnet"
authors = [{name = "Steinmann", email = "rene-steinmann@web.de"}]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["docs/requirements.txt"]}
