[build-system]
requires = ["flit_core >=3.2,<4","numpy>=1.24.2", "scipy>=1.10.1"]
build-backend = "flit_core.buildapi"

[project]
name = "scatseisnet"
authors = [{name = "Steinmann", email = "rene-steinmann@web.de"}]
dynamic = ["version", "description"]
