[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "scatseisnet"
version = "0.1.0"
description = "A short description of the package."
#dependencies =["numpy>=1.24.2", "scipy>=1.10.1"]
authors = [{name = "Steinmann", email = "rene-steinmann@web.de"}]
dynamic = ["version", "description"]
